[package]
name = "onetutorial"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = "2.33"
csv = "1.1"
log4rs = "1.0"
log = "0.4"
lazy_static = "1.4.0"
google-sheets4 = "*"
hyper = "^0.14"
hyper-rustls = "^0.22"
yup-oauth2 = "^5.0"
chrono = "0.4"
openssl = { version = "0.10.32", features = ["vendored"] }
sendmail = "2.0.0"
